# Import Libraries

In [4]:
from bs4 import BeautifulSoup # this module helps in web scrapping.
import requests  # this module helps us to download a web page
import pandas as pd

# Get html text out of URL

In [9]:
url = "https://en.wikipedia.org/wiki/List_of_highest-grossing_films"
r = requests.get(url).text

# Extract required table as Dataframe

In [52]:
soup = BeautifulSoup(r,"html.parser")
table = soup.find_all("table")[0]
data = pd.DataFrame(columns = ["Rank","Peak","Title","Gross","Year"])
for i in table.tbody.find_all('tr'):
    col = i.find_all("td")
    if col != []:
        title = i.find('a',href = True).get('title')
        data = data.append({"Rank" : col[0].text.strip(),"Peak" : col[1].text.strip(),"Title" : title,"Gross" : col[2].text.strip(),"Year" : col[3].text.strip()},ignore_index = True)
data

,Rank,Peak,Title,Gross,Year
0,1,1,Avatar (2009 film),"$2,847,246,203",2009
1,2,1,Avengers: Endgame,"$2,797,501,328",2019
2,3,1,Titanic (1997 film),"$2,187,425,379",1997
3,4,3,Star Wars: The Force Awakens,"$2,068,223,624",2015
4,5,4,Avengers: Infinity War,"$2,048,359,754",2018
5,6,6,Spider-Man: No Way Home,"$1,892,617,772",2021
6,7,3,Jurassic World,"$1,671,537,444",2015
7,8,7,The Lion King (2019 film),"$1,656,943,394",2019
8,9,3,The Avengers (2012 film),"$1,518,812,988",2012
9,10,4,Furious 7,"$1,516,045,911",2015
10,11,10,Frozen II,"$1,450,026,933",2019
11,12,5,Avengers: Age of Ultron,"$1,402,809,540",2015
12,13,9,Black Panther (film),"$1,347,280,838",2018
13,14,3,Harry Potter and the Deathly Hallows â€“ Part 2,"$1,342,025,430",2011
14,15,9,Star Wars: The Last Jedi,"$1,332,539,889",2017
15,16,12,Jurassic World: Fallen Kingdom,"$1,309,484,461",2018
16,17,5,Frozen (2013 film),"F$1,290,000,000",2013
17,18,10,Beauty and the Beast (2017 film),"$1,263,521,126",2017
18,19,15,Incredibles 2,"$1,242,805,359",2018
19,20,11,The Fate of the Furious,"F8$1,238,764,765",2017
20,21,5,Iron Man 3,"$1,214,811,252",2013
21,22,10,Minions (film),"$1,159,398,397",2015
22,23,12,Captain America: Civil War,"$1,153,329,473",2016
23,24,20,Aquaman (film),"$1,148,485,886",2018
24,25,2,The Lord of the Rings: The Return of the King,"$1,146,030,912",2003
25,26,24RK,None,"$1,131,927,996",2019
26,27,23RK,None,"$1,128,274,794",2019
27,28,5RK,None,"$1,123,794,079",2011
28,29,7,Skyfall,"$1,108,561,013",2012
29,30,10,Transformers: Age of Extinction,"$1,104,054,072",2014
30,31,7,The Dark Knight Rises,"$1,081,142,612",2012
31,32,31,Joker (2019 film),"$1,074,251,311",2019
32,33,32,Star Wars: The Rise of Skywalker,"$1,074,144,248",2019
33,34,30,Toy Story 4,"$1,073,394,593",2019
34,35,4TS3,None,"$1,066,969,703",2010
35,36,3,Pirates of the Caribbean: Dead Man's Chest,"$1,066,179,725",2006
36,37,20,Rogue One: A Star Wars Story,"$1,056,057,273",2016
37,38,34,Aladdin (2019 film),"$1,050,693,953",2019
38,39,6,Pirates of the Caribbean: On Stranger Tides,"$1,045,713,802",2011
39,40,24,Despicable Me 3,"$1,034,799,409",2017
40,41,1,Jurassic Park (film),"$1,033,928,303",1993
41,42,22,Finding Dory,"$1,028,570,889",2016
42,43,2,Star Wars: Episode I â€“ The Phantom Menace,"$1,027,044,677",1999
43,44,5,Alice in Wonderland (2010 film),"$1,025,467,110",2010
44,45,24,Zootopia,"$1,023,784,195",2016
45,46,14,The Hobbit: An Unexpected Journey,"$1,017,003,568",2012
46,47,2,Harry Potter and the Philosopher's Stone (film),"$1,006,968,171",2001
47,48,4,The Dark Knight (film),"$1,005,973,645",2008
48,49,10,Harry Potter and the Deathly Hallows â€“ Part 1,"$977,043,483",2010
49,50,19DM2,None,"$970,761,885",2013